**DB課題② データベース定義書作成及びDDL文作成**
kazuyanakata/quelcode-db pull request #2
Opened 2020-09-01 03:13 UTC by kazuyanakata

2020-09-01 07:17 UTC, Yuzunoha commented
各 CREATE TABLE 文の末尾にセミコロンを入れてください。ファイルを一撃で流せるようにしたいので

2020-09-01 07:25 UTC, Yuzunoha commented
(userテーブル)

user_id
user_name
user_mailadress
user_password
user_introduction


これらは

id
name
mail
password
introduction

にしましょう。
カラム名に自分のテーブル名の接頭辞は不要です。mailadressはmailでよいです。

2020-09-01 07:32 UTC, Yuzunoha requested changes

2020-09-01 07:32 UTC, Yuzunoha commented on db/db-challenge2/dbchallenge2.sql
> +  cellphone_number     VARCHAR(13) CHECK (cellphone_number LIKE '%-%'),
```suggestion
  businessphone_number VARCHAR(13),
  cellphone_number     VARCHAR(13),
```

2020-09-01 07:33 UTC, Yuzunoha commented
(userテーブル)
created_at にデフォルト値を設定してください

2020-09-01 07:54 UTC, Yuzunoha commented
他のテーブルもカラム名から接頭辞(プレフィックス)を取り除いてください～
user_
chat_
post_
task_
...

2020-09-01 08:17 UTC, Yuzunoha commented
(chatテーブル)
create_user_id と update_user_id がエクセルとDDLで
NOT NULL のyes/noが食い違っているので合わせてください～

2020-09-01 08:24 UTC, Yuzunoha commented
(postテーブル)
こちらもエクセルとDDLで
not null制約のyes/noの整合性取ってください～

2020-09-01 08:29 UTC, Yuzunoha commented
(taskテーブル)
こちらもエクセルとDDLで
not null制約のyes/noの整合性取ってください～

2020-09-01 08:30 UTC, kazuyanakata commented on db/db-challenge2/dbchallenge2.sql
> +  cellphone_number     VARCHAR(13) CHECK (cellphone_number LIKE '%-%'),
ハイフンを1つ以上含むことをチェックするためにつけました。
課題要件からハイフンをつけることが必須であると汲み取ったのですが、必須ではないということでしょうか？
もしくはINSERT時にチェックするのしょうか？

2020-09-01 13:01 UTC, himaru-jp commented on db/db-challenge2/dbchallenge2.sql
> +  cellphone_number     VARCHAR(13) CHECK (cellphone_number LIKE '%-%'),
課題の要件の意図としては、文字列として扱ってほしいところにありました。
また、データベースで詳細なバリデーションを行うことはほとんどありません。
データベースではデータ同士・レコード同士の整合性を保つことに集中すべきです。
値の詳細なバリデーションはアプリケーション側で担保するのが一般的です。

もしここで、ハイフンをチェックするのであれば、メールアドレスの@なども確認すべきになり、
データベースの制約が複雑化してしまい、あまり現実的ではありません。

2020-09-01 13:09 UTC, himaru-jp requested changes
フラグの場合は、is_deletedなど1が何を表すかはっきり区別できるような名称にしましょう。
is_xxxx(過去形、過去分詞、形容詞など)
また、型についてもchar(1)だとどんな値が入るか制御できないため、
真偽値を保存する場合は、TINYINT(1)を使うと良いです。
TINYINT(1)だと1or0のみが保存できます。

2020-09-01 13:09 UTC, himaru-jp commented on db/db-challenge2/dbchallenge2.sql
> +  user_name            VARCHAR(100) NOT NULL UNIQUE,
ユーザ名をユニークにしてしまうと、同姓同名や同じ名称のユーザが作成できず、
一般的に行われません。
TwitterのユーザIDのような場合は必要ですが、今回はそのような要件は記載されていません。

2020-09-01 13:09 UTC, himaru-jp commented on db/db-challenge2/dbchallenge2.sql
> +  user_mailadress      VARCHAR(100) NOT NULL UNIQUE,
論理削除の場合、一度登録したメールアドレスで二度と登録できなくなってしまいます。
今回の要件ではユニークにすべきではありません。

2020-09-01 13:18 UTC, himaru-jp commented
要件にある通り、トランザクションが利用できるデータベースエンジンの指定を追加しましょう。

2020-09-02 01:52 UTC, kazuyanakata commented on db/db-challenge2/dbchallenge2.sql
> +  cellphone_number     VARCHAR(13) CHECK (cellphone_number LIKE '%-%'),
承知いたしました。
ご回答いただきありがとうございます！

2020-09-02 02:52 UTC, kazuyanakata commented
**コメント箇所の修正を行いました。**

修正箇所
・CREATE TABLE文、末尾にセミコロン追加
・カラム名変更(接頭辞の削除・フラグ名の変更・誤字修正)
・userテーブル、バリデーションの削除
・userテーブル、ユニークの削除
・NOT NULLの整合性を整備
・created_atにデフォルトを追加
・updated_atに自動更新機能追加
・フラグの型及びデフォルトの変更
・ストレージエンジンの指定
・データベース定義書の修正

2020-09-03 01:06 UTC, Yuzunoha commented
レビュー終わったら✓
- [ ] user
- [ ] chat
- [ ] post
- [ ] task
- [ ] chat_participant

2020-09-03 01:09 UTC, Yuzunoha commented
is_parmission_send_file は英文法がよろしくないですね！
is_file_sendable にしましょう！

2020-09-03 01:19 UTC, Yuzunoha commented
task.main_user_id はmainだとちょっと曖昧なので
task.assigned_user_id にしましょう！

2020-09-03 01:37 UTC, kazuyanakata commented
**コメント箇所の修正を行いました。**

修正箇所
・chatテーブル・taskテーブルの物理名変更

2020-09-03 02:44 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-09-03 02:49 UTC, merged